baseURL = 'https://blog.devkom.no'
languageCode = 'en-us'
title = 'Devkom Blog'
theme = 'm10c'
[params]
  author = "Eduardo Pozo"
  description = "A blog about network and automation"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/eduardopozo"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/eduardopozo"
  [[params.social]]
    icon = "linkedin"
    name = "Linedin"
    url = "www.linkedin.com/in/edudppaz"