baseURL = 'https://blog.devkom.no'
languageCode = 'en-us'
title = 'DevKom Blog'
theme = 'm10c'
[params]
  author = "Eduardo Pozo"
  description = "A blog about network and automation"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/eduardopozo"